### ISSUE TITLE
Error build 

### ISSUE THREAD

**Issue by Ummagumma92** [polserver/UOFiddler#76] opened 2021-02-03 16:38 UTC
![image](https://user-images.githubusercontent.com/78493906/106778828-a95b2a00-6646-11eb-9a48-5add99235f2c.png)

![image](https://user-images.githubusercontent.com/78493906/106779155-00f99580-6647-11eb-8fc8-feabf10c7905.png)
 
When i run this program it show me this windows.

**Comment by AsYlum-** [comment] 2021-02-03 16:45
I haven't considered cli dotnet command to build fiddler yet. You need Visual Studio 2019 with Windows Desktop to build.

**Comment by AsYlum-** [comment] 2021-02-03 17:19
I've added few changes so it should build fine now. So if you pull latest from master you can test and let me know how it went. There are ready builds in releases https://github.com/polserver/UOFiddler/releases  

Also You don't need to put UOFiddler in Ultima Online client directory. It's standalone application so it is way better to put it separate folder.

**Comment by Ummagumma92** [comment] 2021-02-04 00:49
I installed virtual studio 2019, and I downloaded the file from your link, but it still gives me the same problem.

Tnx for your help

**Comment by AsYlum-** [comment] 2021-02-04 12:26
Have you used git to pull latest changes in master before you tried to build? Does it fail in Visual Studio too? I'm confused.

**Comment by Arutosio** [comment] 2021-02-05 00:37
i have this problem, can you fix this?

**Comment by AsYlum-** [comment] 2021-02-05 00:39
@Arutosio but what problem? :) Please tell me what is your setup. Do you have Visual Studio 2019 with .net desktop development enabled? Have you tried building project in VS?

**Comment by Arutosio** [comment] 2021-02-05 01:47
> @Arutosio but what problem? :) Please tell me what is your setup. Do you have Visual Studio 2019 with .net desktop development enabled? Have you tried building project in VS?

I have visual studio 2019 with all frameworks of all versions and all packages
![image](https://user-images.githubusercontent.com/30377429/106973519-473c1b00-6753-11eb-9365-72fa194dc3d6.png)
can you implement the dependence inside the program?

**Comment by AsYlum-** [comment] 2021-02-05 14:44
@Ummagumma92 can you paste me fragment of your UOFiddler profile xml file? By default it is located in %appdata%\UoFiddler . There should be at least one file like this Options_default.xml . Can you open this file and paste me the section starting at `<!--Extern Tools settings-->` ?

If you created custom profile then options file will be in format Options_{your profile name}.xml .

**Comment by AsYlum-** [comment] 2021-07-18 12:39
I'm closing this for now as I can't reproduce the problem and there was no answer.

**Closed by AsYlum-** 2021-07-18 12:39 UTC
Labels: question
